import type { Metadata } from "next";
import "../globals.css";
import { getMessages } from "next-intl/server";
import { Providers } from "../Providers";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <NextIntlClientProvider messages={messages}> */}
        <Providers>{children}</Providers>
        {/* </NextIntlClientProvider> */}
      </body>
    </html>
  );
}
