query GetUserDesks($skip: Int = 0, $limit: Int = 30, $filter: DeskQueryFilter) {
  getUserDesks(skip: $skip, limit: $limit, filter: $filter) {
    total
    skip
    limit
    desks {
      id
      name
      description
      icon
      isPublic
      ownerId
      thumbnail
      status
      createdAt
      updatedAt
      flashcardQuantity
    }
  }
}

query getDesks($skip: Int = 0, $limit: Int = 30) {
  getDesks(skip: $skip, limit: $limit) {
    total
    skip
    limit
    desks {
      id
      name
      description
      icon
      isPublic
      thumbnail
      owner {
        id
        name
        email
        avatar
        thumbnail
      }
      flashcardQuantity
    }
  }
}
