type Desk {
  id: ID!
  name: String
  description: String
  icon: String
  isPublic: Boolean
  ownerId: ID
  thumbnail: String
}

type DeskPaginationResult {
  desks: [Desk]
  total: Int
  skip: Int
  limit: Int
}

type SM {
  id: ID!
  name: String
  count: Int
  interval: Float
  EF: Float
  nextDay: String
}

type Flashcard {
  id: ID!
  front_image: String
  front_text: String
  front_sound: String
  back_image: String
  back_text: String
  back_sound: String
  created_at: String
  updated_at: String
  SM: SM
}

type FlashcardPaginationResult {
  flashcards: [Flashcard]
  total: Int
  skip: Int
  limit: Int
}

type Query {
  getFlashcards(
    skip: Int = 0
    limit: Int = 30
    deskId: Int!
  ): FlashcardPaginationResult
  getDesk(id: ID!): Desk
  getDesks(skip: Int = 0, limit: Int = 30): DeskPaginationResult
  getUserDesks(skip: Int = 0, limit: Int = 30): DeskPaginationResult
  getUserDesk(id: ID!): Desk
}
